dist: trusty

sudo: required

language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libaio1

jdk:
- oraclejdk8

services:
  - mysql

install: true

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

script:
- gradle -Ptravis=true clean flywayClean flywayMigrate jooq war
