sudo: required

language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libaio1

jdk:
- oraclejdk8

script:
- gradle -Ptravis=true clean flywayClean flywayMigrate jooq war
